apiVersion: minio.opencontent.ibm.com/v1alpha1
kind: MinioCluster
metadata:
  name: db-minio-ia
  labels:
    app.kubernetes.io/instance: ibm-minio-operator
    app.kubernetes.io/managed-by: ibm-minio-operator
    app.kubernetes.io/name: ibm-minio-operator
  namespace: minio
spec:
  affinity: {}
  affinityMinio: {}
  buckets: []
  clusterDomain: cluster.local
  configPath: /workdir/home/.minio/
  configPathmc: /workdir/home/.mc/
  defaultBucket:
    enabled: true
    name: bucket
    policy: none
    purge: false
  enableCp4dMeteringLabels: true
  environment:
    minioBrowser: 'on'
  existingSecret: ''
  global:
    createdBy: '1000331012'
    deploymentType: Staging
    dockerRegistryPrefix: cp.icr.io/cp/
    environmentType: Python
    image:
      pullPolicy: IfNotPresent
      pullSecret: cp.icr.io
    jobRunId: 1234567-abde-1234-abcde-123456789023
    license: true
    metering:
      addOnId: ''
      cloudpakInstanceId: 750fe2
      productChargedContainers: All
      productCloudpakRatio: '1:1'
      productID: 3be23cc87d094c5f8bd6d73fe149248c
      productMetric: FREE
      productName: Cloud Pak Open
    podLabels:
      slot: slot-name
    projectId: 1234567-abde-1234-abcde-123456789023
    runtimeEnvId: 1234567-abde-1234-abcde-123456789023
    sch:
      enabled: true
    spaceId: 1234567-abde-1234-abcde-123456789023
    storageClassName: portworx-sc
    zenServiceInstanceId: ''
  keep: false
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 20
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1
  minio:
    image:
      image: 'opencontent-minio@sha256:4d5a825ec70a8dce730cc6eb0ca3fabd32659b817b3145eb42444d7f3c30ac51'
      pullPolicy: '{{ tpl ( .Values.global.image.pullPolicy | toString ) .  }}'
  minioClient:
    image:
      image: 'opencontent-minio-client@sha256:4fe33c506f771c46a4f42acb34f80ceaf06708955855ec1939d2e9fb9ae1a9e9'
      pullPolicy: '{{ tpl ( .Values.global.image.pullPolicy | toString ) .  }}'
  mountPath: /workdir/data
  networkPolicy:
    allowExternal: true
    enabled: true
  nodeSelector: {}
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    selector:
      label: ''
      value: ''
    size: 10Gi
    subPath: ''
    useDynamicProvisioning: true
  podAnnotations: {}
  podDisruptionBudget:
    create: true
    maxUnavailable: 1
    minAvailable: ''
  postBucketCreationHookWeight: '0'
  priorityClassName: ''
  rbac:
    create: true
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 1
  replicas: 4
  replicasForDev: 4
  replicasForProd: 4
  resources:
    limits:
      ephemeral-storage: 2Gi
      memory: 2048Mi
    requests:
      cpu: 250m
      ephemeral-storage: 100Mi
      memory: 256Mi
  securityContext:
    creds:
      runAsUser: 523
    minio:
      runAsUser: 999
  service:
    port: 9000
  serviceAccount:
    create: true
    name: ''
  sse:
    enabled: false
    masterKeyName: sseMasterKey
    masterKeySecret: ''
  tls:
    certSecret: ''
    enabled: true
  tolerations: []
  updateStrategy: RollingUpdate
